url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Agua Sabia
email: nadjadenbesten@gmail.com
description: "Expert Assesment and
Consultancy for Hydrological
Impact Analysis using Space and
Ground-based measurements."


# Team names, titles and social links
people:
- name: Nadja den Besten
  pic: 1
  position: Water Scientist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nadja-den-besten-46621025/
    - title: stack-overflow
      url: #

- name: Iñaki Cabo Ibarzabal
  pic: 2
  position: Environmental Educator
  social:
    - title: linkedin
      url: #
    - title: stack-overflow
      url: #

- name: Cueva and Leo
  pic: 3
  position: Happiness Officers
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty